# Generated by Django 4.0.4 on 2022-05-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=50, verbose_name='Ответ пользователя'),
        ),
    ]
