# Generated by Django 4.0.4 on 2022-05-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_poll', '0002_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('text', 'Ответ вводом текста'), ('one_choice', 'Ответ с выбором одного варианта'), ('some_choices', 'Ответ с выбором нескольких вариантов')], max_length=50, verbose_name='Тип вопроса'),
        ),
    ]
